package com.example.report.service;

import java.io.ByteArrayOutputStream;
import java.nio.ByteBuffer;
import java.time.LocalDate;
import java.util.List;

import org.springframework.stereotype.Service;

import com.example.report.dto.AnimalHealthCheckDto;
import com.example.report.repository.interfaces.HealthRepository;
import com.itextpdf.kernel.colors.Color;
import com.itextpdf.kernel.colors.DeviceRgb;
import com.itextpdf.kernel.pdf.*;
import com.itextpdf.layout.*;
import com.itextpdf.layout.element.*;
import com.itextpdf.layout.properties.TextAlignment;

@Service
public class AnimalHealthCheckReportService {
    
    private final HealthRepository healthRepository;

    public AnimalHealthCheckReportService(HealthRepository healthRepository) {
        this.healthRepository = healthRepository;
    }

    public ByteBuffer export2PdfAsBuffer(LocalDate from, LocalDate to) throws Exception {
        List<AnimalHealthCheckDto> healthChecks = healthRepository.findHealthChecks(
            from != null ? from.atStartOfDay() : null,
            to != null ? to.atTime(23, 59, 59) : null
        );

        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        PdfWriter writer = new PdfWriter(baos);
        PdfDocument pdfDoc = new PdfDocument(writer);
        Document document = new Document(pdfDoc);

        // Add title
        Paragraph title = new Paragraph("Animal Health Check Report")
                .setFontSize(16)
                .setBold()
                .setTextAlignment(com.itextpdf.layout.properties.TextAlignment.CENTER);
        document.add(title);

        // Add date range
        String dateRangeText = "Date Range: " + 
            (from != null ? from.toString() : "N/A") + " to " + 
            (to != null ? to.toString() : "N/A");

        Paragraph dateRange = new Paragraph(dateRangeText)
                .setFontSize(12)
                .setTextAlignment(com.itextpdf.layout.properties.TextAlignment.CENTER)
                .setMarginBottom(20);
        document.add(dateRange);

        // Create table with appropriate columns
        Table table = new Table(9).useAllAvailableWidth();

        // Add table headers
        String[] headers = {"ID", "Animal Name", "Species", "Enclosure", "Food Type", "Quantity", "Keeper", "Feeding Time", "Health Status"};
        for (String header : headers) {
            DeviceRgb headerColor = new DeviceRgb(91, 155, 213);
            Paragraph p = new Paragraph(header)
                    .setBold()
                    .setFontSize(11)
                    .setFontColor(headerColor)
                    .setTextAlignment(TextAlignment.CENTER);
            Cell cell = new Cell().add(p)
                    .setBackgroundColor(com.itextpdf.kernel.colors.ColorConstants.LIGHT_GRAY);
            table.addHeaderCell(cell);
        }

        // Add data rows
        for (AnimalHealthCheckDto check : healthChecks) {
            addTableCell(table, check.id());
            addTableCell(table, check.animalName());
            addTableCell(table, check.species());
            addTableCell(table, check.enclosure());
            addTableCell(table, check.weight());
            addTableCell(table, check.healthStatus());
            addTableCell(table, check.activityLevel());
            addTableCell(table, check.checkBy());
            addTableCell(table, check.checkTime());
        }

        document.add(table);

        // Add footer
        Paragraph footerNote = new Paragraph("Note: Health Status is classified as [Excellent / Good / Fair / Poor].")
            .setFontSize(10)
            .setItalic()
            .setMarginTop(20);
        document.add(footerNote);

        Paragraph footerGenerated = new Paragraph("This report is automatically generated by Smart Zoo System.")
            .setFontSize(10)
            .setItalic();
        document.add(footerGenerated);

        document.close();
        baos.close();

        return ByteBuffer.wrap(baos.toByteArray());
    }

    private void addTableCell(Table table, Object value) {
        addTableCell(table, value, TextAlignment.LEFT);
    }

    private void addTableCell(Table table, Object value, TextAlignment alignment) {
        String text = value != null ? value.toString() : "";
        Cell cell = new Cell()
                .add(new Paragraph(text))
                .setPadding(2)
                .setFontSize(11)
                .setTextAlignment(alignment);
        table.addCell(cell);
    }
}
